name = "fortuno"
version = "0.1.0"
license = "BSD-2-Clause-Patent"
author = "Fortuno authors"
maintainer = "aradi@uni-bremen.de"
copyright = "Copyright 2024, Fortuno authors"

[build]
auto-executables = false
auto-tests = true
auto-examples = true
module-naming = false

[install]
library = true

[fortran]
implicit-typing = false
implicit-external = false
source-form = "free"
